### ISSUE TITLE
Active class it's not working

### ISSUE THREAD

**Issue by ruslanguns** [stevesohcot/basic-sample-php-template-example#1]
As you can see in the screenshot below, the section About us it's selected but nav bar does not aply the "active" class properly.

![image](https://user-images.githubusercontent.com/19806968/48214808-ac3c1700-e378-11e8-85f1-2671ca23c9cb.png)

**Comment by irmandos** [comment]
Seems to be working perfectly fine when testing it.

Please make sure the a_config.php is properly configured for how you use it.

![image](https://user-images.githubusercontent.com/5756234/48316286-743c0a80-e5ea-11e8-99d2-4861a1239a54.png)
![image](https://user-images.githubusercontent.com/5756234/48316293-84ec8080-e5ea-11e8-9694-5967e369680a.png)

**Comment by stevesohcot** [comment]
@irmandos - thanks for validating/confirming!

@ruslanguns - try using the _getcwd()_ function to see which directory you're in, and then adjust accordingly.  In my example, I actually made (and, have the code in) a folder called "php-template".

**Comment by ruslanguns** [comment]
Thanks @stevesohcot  & @irmandos ...  Yes, that was an issue with the base URL... I think it will be good to add a BASE_URL setting for dummy people like me lol .
